# *Libra* - Your Database Manager's Favorite Database Manager
> Brady Spears, Los Alamos National Laboratory

---

## About *Libra*
`Libra` is an open-source Python package for managing object-relation-mapped 
(ORM) instances (A.K.A. "Models") across various schemas and various relational 
database backends. `Libra` was developed by Brady Spears with 
contirubtions from Christine Gammans, Jonathan MacCarthy, Richard Alfaro-Diaz,
and Jeremy Webster at Los Alamos National Laboratory.

---

## About this Notebook
This notebook demonstrates standard use cases of `Libra`, including the simple 
initialization of a `Schema` object, the loading and writing of schema 
definitions to/from various built-in schema definition formats, and additional 
simple, showcased functionality. More advanced functionality and customization 
of behavior are included in more focused examples located in the 
[docs/examples](docs/examples) directory.

---

## Declaring and Adding Models to a `Schema` object
"Models," or tables without a "\__tablename\__" attribute, can be defined 
in-line and added to a `Schema` object through the "add_model" decorator. A 
model is composed of `SQLAlchemy` Column objects, which are themselves 
initialized through an `SQLAlchemy` Type object. These Type objects map directly 
map to an appropriate SQL data type, depending on the backend in use. Additional
object-oriented-programming (OOP) functionality is provided through each 
Column objects' keyword arguments, which can embed default values, specify 
beahvior on update of the object, or pass information to `SQLAlchemy's` DDL, 
like whether a column is nullable. At the current iteration, `Libra` only 
supports the declaration of primary keys on unique constraints for models. To 
declare these, a simple "pk" or "uq" attribute can be added to the class, 
denoting the list of column names that the key applies to, creating a composite 
key/constraint in the case that more than one column name is provided.

In [2]:
from datetime import datetime, timezone

from sqlalchemy import Column
from sqlalchemy import DateTime, Float, String

from libra import Schema

# Initialization only needs the Schema name
kbcore = Schema('NNSA KB Core')

@kbcore.add_model
class affiliation:
    net     = Column(String(8), default = '-')
    sta     = Column(String(6), default = '-')
    time    = Column(Float(precision = 53), default = -9999999999.999)
    endtime = Column(Float(precision = 53), default = 9999999999.999)
    lddate  = Column(DateTime, nullable = False, onupdate = datetime.now(timezone.utc),
                default = datetime.now(timezone.utc))

    pk = ['net', 'sta', 'time']

After declaring the structure of the model and adding it to the `Schema` object,
we can establish a connection to the database just as `SQLAlchemy` has 
traditionally done. In order to communicate with the database, however, our 
model will need to map to a table in that database. To do this, we define a new
class inheriting from the model; assigning the "\__tablename\__" attribute, 
which allows `SQLAlchemy's` DDL to interact with the table in the SQL 
environment. Associated with every `Schema` object is an `SQLAlchemy` `Base` 
class, which itself contains information regarding the metadata of the 
current SQL-mapped OOP environment. Here, you can use traditional `SQLAlchemy` 
functionality to create tables given a database engine.

In [3]:
from sqlalchemy import create_engine
from sqlalchemy.orm import Session

connection_str = 'sqlite:///data/libra_intro.db' # In-Memory DB

engine = create_engine(connection_str)
session = Session(engine)

class Affiliation(kbcore.affiliation):
    __tablename__ = 'intro_affiliation'

Affiliation.__table__.drop(engine, checkfirst = True) # Drop table if already there

kbcore.base.metadata.create_all(engine) # Create Table

After creating your table, add data to it in the form of the object, where the 
object is initialized by either positional element instantiation or keyword
element instantiation. Commit the changes to the `SQLAlchemy` session when 
complete.

In [4]:
# Use Positional Instantiation
session.add(Affiliation('USGS', 'ANMO', 144547200., 9999999999.999, datetime.now(timezone.utc))) # Albuquerque, NM
session.add(Affiliation('USGS', 'EDIT', 820454400., 9999999999.999, datetime.now(timezone.utc))) # Edith, TN
session.add(Affiliation('USGS', 'HAV', -552355200., 9999999999.999, datetime.now(timezone.utc))) # Havilah, CA

# Or use Keyword Instantiation (will use default column values)
session.add(Affiliation(net = 'USGS', sta = 'SGM', time = 94694400)) # Silver Gate, MT

session.commit()

After commiting the data to your table, you can regurgitate the data using a 
database query. Simply call the "query()" method on your database session, and 
pass the table. Use the "filter()" factory method to return a list the objects, 
with parameters to reflect the values contained in the columns of the SQL table.

In [5]:
query = session.query(Affiliation).filter(Affiliation.time >= 0.)

list(query) # List out each row of the query

[Affiliation(net='USGS', sta='ANMO', time=144547200.0),
 Affiliation(net='USGS', sta='EDIT', time=820454400.0),
 Affiliation(net='USGS', sta='SGM', time=94694400.0)]

All CRUD operations are supported natively through `SQLAlchemy`, including the 
ability to delete row(s) from the table you've created. Here's an example that 
filters out a single row in the table and deletes it from the database before 
reading back in all rows of that table to show it was deleted.

In [6]:
aff_to_remove = session.query(Affiliation).filter(Affiliation.sta == 'EDIT').first()

session.delete(aff_to_remove)
session.commit()

list(session.query(Affiliation).all())

[Affiliation(net='USGS', sta='ANMO', time=144547200.0),
 Affiliation(net='USGS', sta='HAV', time=-552355200.0),
 Affiliation(net='USGS', sta='SGM', time=94694400.0)]

---

## Reading in Plain-Text Schema Definitions as a `Schema` object

`Libra` comes pre-packaged with support for encoding and decoding the models, 
columns, and constraints contained within your schema as a plain-text format 
known as a "schema-definition format." Supported formats include Python 
dictionaries containing only strings, YAML files, and specifically-formatted 
database tables. This section will cover some high-level details about each one 
and provide an example of how to decode the respective format, perform various 
database functions on the models deriving from that format, and encode the 
models back into that format.

### Python Dictionary Schema Definition Format

Schemas, or sets of related database tables, can be loaded in from Python 
dictionaries that contain plain text. In order to do this, import the 
`DictionarySettings` object and specify the 'dictionary' parameter.

In [7]:
from libra import Schema, DictionarySettings
from data.kbcore_dict import KBCORE_DICT

settings = DictionarySettings(dictionary = KBCORE_DICT)

schema = Schema('NNSA KB Core').load(settings)

class Affiliation(schema.affiliation):
    __tablename__ = 'affiliation'

class Sitechan(schema.sitechan):
    __tablename__ = 'sitechan'

aff = Affiliation(net = 'SN', sta = 'ANMO')
sitec = Sitechan(sta = 'ANMO', chan = 'BHZ')

print(aff)
print(sitec)

Affiliation(net='SN', sta='ANMO', time=-9999999999.999, endtime=9999999999.999, lddate=2025-09-25 16:07:51.144359+00:00)
Sitechan(sta='ANMO', chan='BHZ', ondate=-1, chanid=-1, offdate=2286324, ctype=None, edepth=-1.0, hang=-1.0, vang=-1.0, descrip=None, lddate=2025-09-25 16:07:51.144359+00:00)

### YAML File Dictionary Schema Definition Format

Schemas can be loaded in from a correctly-formatted YAML file encoded in plain 
text. In order to do this, import the `YAMLFileSettings` object and define the 
'file' parameter.

In [ ]:
from libra import Schema, YAMLFileSettings

settings = YAMLFileSettings(file = 'file')

### Database Table Schema Definition Format

---

## Additional Functionality and Built-in Model Mixin Support

`Libra` uses `SQLAlchemy's` flexibility to provide some useful functionality in 
the form of "Mix-ins," or classes that contain methods or attributes that 
augment a Model or Table's behavior in the OOP environment. Built-in support is 
provided for:

1. Reading and writing lists of model objects to and from flat files
2. Converting lists of model objects to and from Pandas DataFrame objects
3. Performing quality control (QC) on values contained in model objects

Support for some of these is facilitated through additional parameters passed 
at the Column-object level when declaring a model and adding it to a `Schema`. 
In order to add associative parameters with a `SQLAlchemy` Column object, you 
can add those parameters in the Column's "info" dictionary. See the below 
in-line model declaration script for an example of how we inject custom 
parameters into a Column's "info" dictionary:

In [8]:
from datetime import datetime, timezone

from sqlalchemy import Column
from sqlalchemy import DateTime, Integer, Float, String
from sqlalchemy import create_engine
from sqlalchemy.orm import Session

from libra import Schema

connection_str = 'sqlite:///data/libra_intro.db' # In-Memory DB

engine = create_engine(connection_str)
session = Session(engine)

antelope = Schema('Antelope')

@antelope.add_model
class event:
    evid = Column(Integer, nullable = False, info = {'format' : '8d', 'gt' : 0})
    evname = Column(String(length = 15), default = '-', info = {'format' : '15.15s'})
    prefor = Column(Integer, nullable = False, info = {'format' : '8d', 'gt' : 0})
    auth = Column(String(length = 15), default = '-', info = {'format' : '15.15s'})
    commid = Column(Integer, default = -1, info = {'format' : '8d'})
    lddate = Column(DateTime, nullable = False, onupdate = datetime.now(timezone.utc), 
                    default = datetime.now(timezone.utc), info = {'format' : '%Y-%m-%d %H:%M:%S'})

    pk = ['evid']

@antelope.add_model
class origin:
    lat = Column(Float(precision = 24), default = -999.0, info = {'format' : '9.4f'})
    lon = Column(Float(precision = 24), default = -999.0, info = {'format' : '9.4f'})
    depth = Column(Float(precision = 24), default = -999.0, info = {'format' : '9.4f'})
    time = Column(Float(precision = 53), nullable = False, info = {'format' : '17.5f'})
    orid = Column(Integer, nullable = False, info = {'format' : '8d'})
    evid = Column(Integer, default = -1, info = {'format' : '8d'})
    jdate = Column(Integer, default = -1, info = {'format' : '9d'})
    nass = Column(Integer, default = -1, info = {'format' : '4d'})
    ndef = Column(Integer, default = -1, info = {'format' : '4d'})
    ndp = Column(Integer, default = -1, info = {'format' : '4d'})
    grn = Column(Integer, default = -1, info = {'format' : '8d'})
    srn = Column(Integer, default = -1, info = {'format' : '8d'})
    etype = Column(String(2), default = '-', info = {'format' : '2.2s'})
    review = Column(String(4), default = '-', info = {'format' : '4.4s'})
    depdp = Column(Float(precision = 24), default = -999.0, info = {'format' : '9.4f'})
    dtype = Column(String(1), nullable = False, info = {'format' : '1.1s'})
    mb = Column(Float(precision = 24), default = -999.0, info = {'format' : '7.2f'})
    mbid = Column(Integer, default = -1, info = {'format' : '8d'})
    ms = Column(Float(precision = 24), default = -999.0, info = {'format' : '7.2f'})
    msid = Column(Integer, default = -1, info = {'format' : '8d'})
    ml = Column(Float(precision = 24), default = -999.0, info = {'format' : '7.2f'})
    mlid = Column(Integer, default = -1, info = {'format' : '8d'})
    algorithm = Column(String(15), default = '-', info = {'format' : '15.15s'})
    auth = Column(String(15), default = '-', info = {'format' : '15.15s'})
    commid = Column(Integer, default = -1, info = {'format' : '8d'})
    lddate = Column(DateTime, nullable = False, onupdate = datetime.now(timezone.utc), 
                    default = datetime.now(timezone.utc), info = {'format' : '%Y-%m-%d %H:%M:%S'})

    pk = ['orid', 'depth', 'lat', 'lon', 'nass', 'ndef', 'time']


class Event(antelope.event):
    __tablename__ = 'event'

class Origin(antelope.origin):
    __tablename__ = 'origin'

Event.__table__.drop(engine, checkfirst = True) # Drop tables if already there
Origin.__table__.drop(engine, checkfirst = True)

antelope.base.metadata.create_all(engine)

origins = [
    Origin(orid = 7539997,lat = 37.0517, lon = -118.0784, depth = 4.622, time = 1076422702.04032, nass = 9, ndef = 7, etype = 'eq', dtype = 'f'),
    Origin(orid = 1919065, lat = 37.0522, lon = -121.483, depth = 8.39, time = 1166774205.57, nass = 30, ndef = 78, etype = 'eq', dtype = 'f'),
    Origin(orid = 21814291, lat = 37.0597, lon = -118.3235, depth = 13.5133, time = 1103856323.32, nass = 15, ndef = 13, etype = 'eq', dtype = 'f')
]

events = [
    Event(evid = 6242047, prefor = 7539997, auth = 'bspears-LANL'),
    Event(evid = 7916, prefor = 1919065, auth = 'bspears-LANL'),
    Event(evid = 8420985, prefor = 21814291, auth = 'bspears-LANL')
]

[session.add(og) for og in origins]
[session.add(ev) for ev in events]

session.commit()

---

### Reading and Writing Flat Files

`Libra` comes pre-packaged with the abiltiy to read and write flat files, or 
space-delimitted, specifically-formatted, plain-text files. These files are 
particularly useful for mutli-institutional teams who need to share data quickly 
but may be operating different database backends. As an example, we can load the 
[docs/examples/data/origin.antelope](docs/examples/data/origin.antelope) flat 
file and view the contents:

In [9]:
with open('data/origin.antelope', 'r') as f:
    lines = f.readlines()

print(*[line for line in lines])

  37.0999 -118.2095    3.9490  1464958110.76208 32790566       -1   2016155    6    6   -1       40        3 eq -    -999.0000 f -999.00       -1 -999.00       -1 -999.00       -1 -               -                     -1 2025-09-08 18:18:31
   37.1043 -118.6818   11.0981  1041399713.77288 33143678       -1   2003001   17   17   -1       40        3 eq -    -999.0000 f    0.70 44727835 -999.00       -1 -999.00       -1 -               -                     -1 2025-09-08 18:18:31
   37.1099 -118.2294   10.2982  1164504053.52121 33150002       -1   2006330   41   28   -1       40        3 eq -    -999.0000 f    2.68 33639742 -999.00       -1 -999.00       -1 -               -                     -1 2025-09-08 18:18:31
   37.1152 -118.4467   13.7218  1220454394.25648 32880159       -1   2008247   14   13   -1       39        3 eq -    -999.0000 f    1.43 44754326 -999.00       -1 -999.00       -1 -               -                     -1 2025-09-08 18:18:31

Now that we have our lines read out as a list of strings, we can use `Libra's` from_string() function to get the string into a list of Origin objects:

In [10]:
from libra.func import from_string

origins = from_string(Origin(), lines)

print(*[og for og in origins], sep='\n')

Origin(lat=37.0999, lon=-118.2095, depth=3.949, time=1464958110.76208, orid=32790566, evid=-1, jdate=2016155, nass=6, ndef=6, ndp=-1, grn=40, srn=3, etype='eq', review='-', depdp=-999.0, dtype='f', mb=-999.0, mbid=-1, ms=-999.0, msid=-1, ml=-999.0, mlid=-1, algorithm='-', auth='-', commid=-1, lddate=2025-09-08 18:18:31)
Origin(lat=37.1043, lon=-118.6818, depth=11.0981, time=1041399713.77288, orid=33143678, evid=-1, jdate=2003001, nass=17, ndef=17, ndp=-1, grn=40, srn=3, etype='eq', review='-', depdp=-999.0, dtype='f', mb=0.7, mbid=44727835, ms=-999.0, msid=-1, ml=-999.0, mlid=-1, algorithm='-', auth='-', commid=-1, lddate=2025-09-08 18:18:31)
Origin(lat=37.1099, lon=-118.2294, depth=10.2982, time=1164504053.52121, orid=33150002, evid=-1, jdate=2006330, nass=41, ndef=28, ndp=-1, grn=40, srn=3, etype='eq', review='-', depdp=-999.0, dtype='f', mb=2.68, mbid=33639742, ms=-999.0, msid=-1, ml=-999.0, mlid=-1, algorithm='-', auth='-', commid=-1, lddate=2025-09-08 18:18:31)
Origin(lat=37.1152, lon=-118.4467, depth=13.7218, time=1220454394.25648, orid=32880159, evid=-1, jdate=2008247, nass=14, ndef=13, ndp=-1, grn=39, srn=3, etype='eq', review='-', depdp=-999.0, dtype='f', mb=1.43, mbid=44754326, ms=-999.0, msid=-1, ml=-999.0, mlid=-1, algorithm='-', auth='-', commid=-1, lddate=2025-09-08 18:18:31)

Let's go ahead and add these new origins that we've parsed from the flat file into the database and then read and display them using Pandas. We should expect a DataFrame object of 7 rows and 26 columns.

In [11]:
[session.add(og) for og in origins]
session.commit()

import pandas as pd

df = pd.read_sql_table('origin', engine)

display(df)

,lat,lon,depth,time,orid,evid,jdate,nass,ndef,ndp,...,mb,mbid,ms,msid,ml,mlid,algorithm,auth,commid,lddate
0,37.0517,-118.0784,4.6220,1.076423e+09,7539997,-1,-1,9,7,-1,...,-999.00,-1,-999.0,-1,-999.0,-1,-,-,-1,2025-09-25 16:08:13.001457
1,37.0522,-121.4830,8.3900,1.166774e+09,1919065,-1,-1,30,78,-1,...,-999.00,-1,-999.0,-1,-999.0,-1,-,-,-1,2025-09-25 16:08:13.001457
2,37.0597,-118.3235,13.5133,1.103856e+09,21814291,-1,-1,15,13,-1,...,-999.00,-1,-999.0,-1,-999.0,-1,-,-,-1,2025-09-25 16:08:13.001457
3,37.0999,-118.2095,3.9490,1.464958e+09,32790566,-1,2016155,6,6,-1,...,-999.00,-1,-999.0,-1,-999.0,-1,-,-,-1,2025-09-08 18:18:31.000000
4,37.1043,-118.6818,11.0981,1.041400e+09,33143678,-1,2003001,17,17,-1,...,0.70,44727835,-999.0,-1,-999.0,-1,-,-,-1,2025-09-08 18:18:31.000000
5,37.1099,-118.2294,10.2982,1.164504e+09,33150002,-1,2006330,41,28,-1,...,2.68,33639742,-999.0,-1,-999.0,-1,-,-,-1,2025-09-08 18:18:31.000000
6,37.1152,-118.4467,13.7218,1.220454e+09,32880159,-1,2008247,14,13,-1,...,1.43,44754326,-999.0,-1,-999.0,-1,-,-,-1,2025-09-08 18:18:31.000000

---

### Pandas DataFrame read/write Support

`Libra` also comes prepackaged with the ability to convert your models to and 
from `Pandas` DataFrame objects. Use the 'to_dframe()' and 'from_dframe' methods 
to use this functionality:

In [12]:
from libra.func import to_dframe

query = session.query(Event).all()

event_dframe = to_dframe(query)

display(event_dframe)

      evid evname    prefor          auth  commid                     lddate
0     7916      -   1919065  bspears-LANL      -1 2025-09-25 16:08:13.001457
1  6242047      -   7539997  bspears-LANL      -1 2025-09-25 16:08:13.001457
2  8420985      -  21814291  bspears-LANL      -1 2025-09-25 16:08:13.001457

In [13]:
import pandas as pd

from libra.func import from_dframe

newevent_dframe = pd.DataFrame(
    {'evid' : 1192608, 'evname' : 'Small Earthquake', 'prefor' : 33150002, 'auth' : 'bspears-LANL', 'commid' : -1, 'lddate' : datetime(2025, 9, 8, 18, 55, 57)},
    {'evid' : 1435581, 'evname' : 'Smaller Earthquake', 'prefor' : 32880159, 'auth' : 'bspears-LANL', 'commid' : -1, 'lddate' : datetime(2025, 9, 8, 18, 55, 57)}
)

events = from_dframe(newevent_dframe, Event)

print(*[ev for ev in events], sep = '\n')

Event(evid=1192608, evname='Small Earthquake', prefor=33150002, auth='bspears-LANL', commid=-1, lddate=2025-09-08T18:55:57.000000)
Event(evid=1192608, evname='Small Earthquake', prefor=33150002, auth='bspears-LANL', commid=-1, lddate=2025-09-08T18:55:57.000000)
Event(evid=1192608, evname='Small Earthquake', prefor=33150002, auth='bspears-LANL', commid=-1, lddate=2025-09-08T18:55:57.000000)
Event(evid=1192608, evname='Small Earthquake', prefor=33150002, auth='bspears-LANL', commid=-1, lddate=2025-09-08T18:55:57.000000)
Event(evid=1192608, evname='Small Earthquake', prefor=33150002, auth='bspears-LANL', commid=-1, lddate=2025-09-08T18:55:57.000000)
Event(evid=1192608, evname='Small Earthquake', prefor=33150002, auth='bspears-LANL', commid=-1, lddate=2025-09-08T18:55:57.000000)

---

### Quality Control Support for Models

`Libra` comes pre-packaged with support for performing simple quality control 
on the values contained in columns of a model, while at the same time not being 
so strict as to prevent the insertion of the data in the model; because often, 
it is desirable to get the data in the desired form and clean it from that 
point. QC functionality is supported at the classmethod level and the functional 
level, and will derive a set of quality control checks based on the keywords 
passed to each Column object's info dictionary. Valid built-in checks include:

1. Setting a 'greater than' parameter on a numeric column
2. Setting a 'greater than or equal to' parameter on a numeric column
3. Setting a 'less than' parameter on a numeric column
4. Setting a 'less than or equal to' parameter on a numeric column
5. Setting an 'equal to' parameter on a column's value
6. Setting a 'not equal to' parameter on a column's value
7. Setting an exclusive range on a numeric column
8. Setting an inclusive range on a numeric column 
9. Setting a regex value on a stringified column
10. Setting a finite number of 'options' for the value contained within a column
11. Setting a minimum string length value on a stringified column
12. Setting a maximum string length value on a stringified column

Not every column needs to have a check associated with it and one column can 
have multiple checks applied to it. All is gathered in a `QCResult` object, 
which can return a print out of which checks were performed and if the values 
for a given model either passed or failed the check.

In [14]:
from libra.func import simple_qc

kbcore = Schema('NNSA KB Core')

@kbcore.add_model
class site:
    sta = Column(String(6), info = {'format' : '6.6s', 'regex' : r'[A-Z0-9\-][A-Z0-9x\-\*+]+$'})
    ondate = Column(Integer, default = -1, info = {'format' : '8d', 'range_in' : [-1, 2286324]})
    offdate = Column(Integer, default = 2286324, info = {'format' : '8d', 'range_in' : [-1, 2286324]})
    lat = Column(Float(precision = 53), default = -999., info = {'format' : '11.6f', 'range_in' : [-90, 90]})
    lon = Column(Float(precision = 53), default = -999., info = {'format' : '11.6f', 'range_in' : [-180, 180]})
    elev = Column(Float(precision = 24), default = -999., info = {'format' : '9.4f', 'range_in' : [-10, 10]})
    staname = Column(String(50), info = {'format' : '50.50s'})
    statype = Column(String(4), info = {'format' : '4.4s', 'options' : ['ss', 'ar']})
    refsta = Column(String(6), info = {'format' : '6.6s', 'regex' : r'[A-Z0-9\-][A-Z0-9x\-\*+]+$'})
    dnorth = Column(Float(precision = 24), nullable = False, default = 0., info = {'format' : '9.4f', 'range_in' : [-2e4, 2e4]})
    deast = Column(Float(precision = 24), nullable = False, default = 0., info = {'format' : '9.4f', 'range_in' : [-2e4, 2e4]})
    lddate = Column(DateTime, nullable = False, onupdate = datetime.now(timezone.utc), default = datetime.now(timezone.utc), info = {'format' : '%Y-%m-%d %H:%M:%S'})

    pk = ['sta', 'ondate']

class Site(kbcore.site):
    __tablename__ = 'site'

site_entries = [
    Site(sta = 'ANMO', ondate = 2002324, lat = 34.94591, lon = -106.4572, elev = 1.82, staname = 'Albuquerque, New Mexico, USA', statype = 'ss', refsta = 'ANMO'),
    Site(sta = 'BASO', ondate = -2, offdate = 2286324, lat = 44.01331, lon = -81.66482, elev = 2100, staname = 'Ashfield, Ontario, Canada', statype = 'ss', refsta = 'BASO'),
    Site(sta = 'TPFO', ondate = 2018306, offdate = 2286324, lat = 33.606, lon = -116.4544, elev = 1.275, staname = 'Pinon Flat Observatory TA, California, USA', statype = 'sta', refsta = 'tPFO')
]

qc_results = simple_qc(site_entries)

for i, result in enumerate(qc_results):
    print(f'{site_entries[i]}\n----------\n{result}\n==========\n')

Site(sta='ANMO', ondate=2002324, offdate=2286324, lat=34.94591, lon=-106.4572, elev=1.82, staname='Albuquerque, New Mexico, USA', statype='ss', refsta='ANMO', dnorth=0.0, deast=0.0, lddate=2025-09-25 16:11:21.355836+00:00)
----------
sta:
  - functools.partial(<function <lambda> at 0x7f8116938cc0>, ref='[A-Z0-9\\-][A-Z0-9x\\-\\*+]+$'): PASS
ondate:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-1, 2286324]): PASS
offdate:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-1, 2286324]): PASS
lat:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-90, 90]): PASS
lon:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-180, 180]): PASS
elev:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-10, 10]): PASS
statype:
  - functools.partial(<function <lambda> at 0x7f8116938d60>, ref=['ss', 'ar']): PASS
refsta:
  - functools.partial(<function <lambda> at 0x7f8116938cc0>, ref='[A-Z0-9\\-][A-Z0-9x\\-\\*+]+$'): PASS
dnorth:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-20000.0, 20000.0]): PASS
deast:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-20000.0, 20000.0]): PASS

==========

Site(sta='BASO', ondate=-2, offdate=2286324, lat=44.01331, lon=-81.66482, elev=2100, staname='Ashfield, Ontario, Canada', statype='ss', refsta='BASO', dnorth=0.0, deast=0.0, lddate=2025-09-25 16:11:21.355836+00:00)
----------
sta:
  - functools.partial(<function <lambda> at 0x7f8116938cc0>, ref='[A-Z0-9\\-][A-Z0-9x\\-\\*+]+$'): PASS
ondate:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-1, 2286324]): FAIL
offdate:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-1, 2286324]): PASS
lat:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-90, 90]): PASS
lon:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-180, 180]): PASS
elev:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-10, 10]): FAIL
statype:
  - functools.partial(<function <lambda> at 0x7f8116938d60>, ref=['ss', 'ar']): PASS
refsta:
  - functools.partial(<function <lambda> at 0x7f8116938cc0>, ref='[A-Z0-9\\-][A-Z0-9x\\-\\*+]+$'): PASS
dnorth:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-20000.0, 20000.0]): PASS
deast:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-20000.0, 20000.0]): PASS

==========

Site(sta='TPFO', ondate=2018306, offdate=2286324, lat=33.606, lon=-116.4544, elev=1.275, staname='Pinon Flat Observatory TA, California, USA', statype='sta', refsta='tPFO', dnorth=0.0, deast=0.0, lddate=2025-09-25 16:11:21.355836+00:00)
----------
sta:
  - functools.partial(<function <lambda> at 0x7f8116938cc0>, ref='[A-Z0-9\\-][A-Z0-9x\\-\\*+]+$'): PASS
ondate:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-1, 2286324]): PASS
offdate:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-1, 2286324]): PASS
lat:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-90, 90]): PASS
lon:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-180, 180]): PASS
elev:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-10, 10]): PASS
statype:
  - functools.partial(<function <lambda> at 0x7f8116938d60>, ref=['ss', 'ar']): FAIL
refsta:
  - functools.partial(<function <lambda> at 0x7f8116938cc0>, ref='[A-Z0-9\\-][A-Z0-9x\\-\\*+]+$'): FAIL
dnorth:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-20000.0, 20000.0]): PASS
deast:
  - functools.partial(<function <lambda> at 0x7f8116938c20>, ref=[-20000.0, 20000.0]): PASS

==========